project:
  type: website

website:
  title: "Genomic Data Science"
  navbar:
    right:
      - about.qmd
      - text: Leadership Team 
        href: about-team.qmd
      - icon: github
        href: https://github.com/jhugenomicdatascience

format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

execute:
  freeze: auto



